"""add send_to and has_delayed_taks filed to MassSendMessage

Revision ID: 671621679535
Revises: faed75cbc667
Create Date: 2025-07-01 21:15:32.979076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671621679535'
down_revision: Union[str, None] = 'faed75cbc667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_send_message', sa.Column('send_to', sa.String(), nullable=True))
    op.add_column('mass_send_message', sa.Column('has_delayed_task', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_send_message', 'has_delayed_task')
    op.drop_column('mass_send_message', 'send_to')
    # ### end Alembic commands ###
