"""add delay_time filed to MassSendMessage

Revision ID: faed75cbc667
Revises: 366a112d0755
Create Date: 2025-07-01 16:42:28.472740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faed75cbc667'
down_revision: Union[str, None] = '366a112d0755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_send_message', sa.Column('delay_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_send_message', 'delay_time')
    # ### end Alembic commands ###
